module Crystal
  module CharacterConstants
    ASTERISC = '*'
    EQUALS_CHAR = '='
    NEW_LINE_CHAR = '\n'
    CARRIAGE_RETURN = '\r'
    INTERROGATION_CHAR = '?'
    EXCLAMATION_CHAR = '!'
    DOUBLE_QUOTES_CHAR = '"'
    OPEN_KEYS_CHAR = '{'
    CLOSE_KEYS_CHAR = '}'
    PERCENT_CHAR = '%'
    ZERO_CHAR = '0'
    ONE_CHAR = '1'
    TWO_CHAR = '2'
    THREE_CHAR = '3'
    FOUR_CHAR = '4'
    FIVE_CHAR = '5'
    SIX_CHAR = '6'
    SEVEN_CHAR = '7'
    EIGHT_CHAR = '8'
    NINE_CHAR = '9'
    COMMA_CHAR = ','
    HASHTAG_CHAR = '#'
    MINUS_THAN_CHAR = '<'
    GREATER_THAN_CHAR = '>'
    OPEN_PARENTHESIS_CHAR = '('
    CLOSE_PARENTHESIS_CHAR = ')'
    SEMI_COLON_CHAR = ';'
    OPEN_CORCHETE = '['
    CLOSE_CORCHETE_CHAR = ']'
    PLUS_CHAR = '+'
    MINUS_CHAR = '-'
    GUION_BAJO_CHAR = '_'
    PIPE_CHAR = '|'
  end
end
